### ISSUE TITLE
sessionMagicLinkKey default value typo

### ISSUE THREAD

**Issue by atoi** [pbteja1998/remix-auth-email-link#35]
### Describe the bug

The class documentation tells the default value for `sessionMagicLinkKey` uses camelCase.
```ts
  /**
   * The key on the session to store the magic link.
   * @default "auth:magicLink"
   */
  sessionMagicLinkKey?: string
```

The code examples in the README use lowercase.
```ts
  // This session key `auth:magiclink` is the default one used by the EmailLinkStrategy
  // you can customize it passing a `sessionMagicLinkKey` when creating an
  // instance.
  return json({
    magicLinkSent: session.has('auth:magiclink'),
    magicLinkEmail: session.get('auth:email'),
  })
```

Here we can see, that lowercase is the right way to go if you want make things work.
https://github.com/pbteja1998/remix-auth-email-link/blob/main/src/index.ts#L173
```ts
this.sessionMagicLinkKey = options.sessionMagicLinkKey ?? 'auth:magiclink'
```

So, I suppose either the docs or the default value should be corrected.  
Otherwise some people may have quite a bit of fun debugging their auth code, trying to figure out why the link is not there.

### Your Example Website or App

Does not really need stackblitz

### Steps to Reproduce the Bug or Issue

1. Look here https://github.com/pbteja1998/remix-auth-email-link/blob/main/src/index.ts#L100
1. Then look here https://github.com/pbteja1998/remix-auth-email-link/blob/main/src/index.ts#L173

### Expected behavior

- I would expect to actually get the magic link value without surprises

### Platform

- OS: macOS
- Browser: Chrome
- Version: 110.0.5481.177

**Comment by pbteja1998** [comment]
Thank you. Fixed it!
